# Site settings
title: Mayjs
email:
description: Personal blog about some of my projects
baseurl:
url:
twitter_username:
github_username: mayjs

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman